# Generated by Django 3.2 on 2022-04-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20220404_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('unit', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='setup.exerciseunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
