# Generated by Django 3.2 on 2022-04-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='setup.exerciseunit'),
        ),
    ]
