# Generated by Django 3.2 on 2022-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_alter_exercise_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseunit',
            name='name',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
