# Generated by Django 3.2 on 2022-04-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_auto_20220414_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='unit',
            field=models.CharField(max_length=30),
        ),
    ]
