# Generated by Django 3.2 on 2022-04-14 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_alter_exercise_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='unit',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.SET_DEFAULT, to='setup.exerciseunit'),
        ),
    ]
