# Generated by Django 3.2 on 2022-04-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_alter_exercise_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
