# Generated by Django 3.2 on 2022-04-17 17:14

from django.db import migrations, models
import django.db.models.deletion
import setup.models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_alter_exercise_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='unit',
            field=models.ForeignKey(default=setup.models.get_default_exercise_unit, on_delete=django.db.models.deletion.SET_DEFAULT, to='setup.exerciseunit'),
        ),
    ]
