# Generated by Django 3.2 on 2022-05-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_alter_exercise_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
