# Generated by Django 3.2 on 2022-05-20 20:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'The Workout name is not unique'}, max_length=30, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date', models.DateField(unique=True)),
                ('comment', models.TextField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ManyToManyField(blank=True, related_name='workouts', to='main.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reps', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('sets', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='setup.exercise')),
                ('reps_unit', models.ForeignKey(blank=True, default=main.models.get_default_reps_unit, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='setup.repsunit')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='main.workout')),
            ],
        ),
    ]
