# Generated by Django 3.2 on 2022-04-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_collection_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
