# Generated by Django 3.2 on 2022-04-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_collection_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(error_messages={'unique': 'The Workout name is not unique'}, max_length=30, unique=True),
        ),
    ]
