# Generated by Django 3.2 on 2022-04-25 06:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_alter_exercise_unit'),
        ('main', '0004_alter_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='reps',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='reps_unit',
            field=models.ForeignKey(blank=True, default=main.models.get_default_reps_unit, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='setup.repsunit'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
