# Generated by Django 3.2 on 2022-04-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_alter_exercise_unit'),
        ('main', '0005_auto_20220425_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='setup.exercise'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='main.workout'),
        ),
    ]
